<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AmazonEcommerce_BusinessEntities\AmazonEcommerce_BusinessEntities.csproj" />
    <ProjectReference Include="..\AmazonEcommerce_DbConnectivity\AmazonEcommerce_DbConnectivity.csproj" />
  </ItemGroup>

</Project>
